// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Ensure DATABASE_URL is defined
const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

export default defineConfig({
  // Schema path relative to the backend directory (WORKDIR in Docker)
  schema: "prisma/schema.prisma",
  migrations: {
    // Migrations path relative to the backend directory
    path: "prisma/migrations",
  },
  datasource: {
    // DATABASE_URL must be available at build time
    // For SQLite in Docker: file:./dev.db (relative to WORKDIR)
    url: databaseUrl,
  },
});
